export const HELLO = "hello";
export const COLORS = {
  softPink: "#ff81d3",
  hotPink: "#ff68ca",
  softPurple: "#b6b0ff",
  hotPurple: "#c180ff",
  hotCyan: "#14e7ff",
  softCyan: "#92dce5",
  hotAqua: "#39d4bb",
  softAqua: "#399999",
  hotGreen: "#48ff14",
  softGreen: "#2fb863",
  hotYellow: "#eeff14",
  hotOrange: "#dfae45",
  softOrange: "#e9c194",
  hotRed: "#dd7474",
  softRed: "#e99999",
};
export const TIME = [
  "0",
  "0:1",
  "0:2",
  "1:0",
  "1:2",
  "2:0",
  "2:2",
  "3:0",
  "3:2",
  "4:0",
  "4:2",
  "5:0",
  "5:2",
  "6:0",
  "6:2",
  "7:0",
  "7:2",
  "8:0",
];
export const SONG_STRUCTURE_PARTS = [
  "Intro",
  "aPart",
  "anotherPart",
  "yetAnotherPart",
  "somePart",
  "Chorus",
  "Bridge",
  "Outro",
];
export const SONG_STRUCTURE_ADDITIONS = [
  "Transpose up one whole step",
  "All instruments cut out; if you're using them, only singing, percussion, and optionally, bass, remain",
  "Add a counter-melody with an unexpected instrument, such as flute, French horn, or steel drum",
  "Consider adding a sample here. Be careful, and avoid cliche",
  "Add handclaps",
  "If there are drums, make them go half-time here",
];
